# ===== Server =====
server.port=${PORT:8080}
server.servlet.context-path=/api/v1.0

# ===== Datasource (Render Postgres EXTERNAL) =====
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# (????? ??? Render/??????, ????? Hibernate ?? ??????? ??????? ?? ??????????, ????? ???????? ???)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===== Hikari (???? ?????????? ? ??????) =====
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0

# ===== Mail =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USERNAME:}
spring.mail.password=${GMAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.from=${GMAIL_FROM_EMAIL:}

# ===== JWT =====
jwt.secret=${JWT_SECRET}

# ===== App =====
money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL:}

logging.level.org.springframework.security=INFO