# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/moneymanager
spring.datasource.username=root
spring.datasource.password=group_bb

# Context Path
server.servlet.context-path=/api/v1.0

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=amir2008-super-secret-key-for-jwt-token-generation-2024

logging.level.org.springframework.security=DEBUG

money.manager.frontend.url=${MONEY_MANAGER_FRONTEND_URL}

app.activation.url=${MONEY_MANAGER_BACKEND_URL}

spring.profiles.active=prod